services:
    # ===================== PostgreSQL =====================
    app-pos-postgres:
        image: postgres:16
        container_name: app-pos-postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: appposdb
        ports:
          - "5434:5432"
        volumes:
          - app-pos-pgdata:/var/lib/postgresql/data
        networks:
          - app-pos-network
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          timeout: 5s
          retries: 5
    # ===================== REDIS =====================
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - app-pos-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
    
    redis-insight:
        image: redis/redisinsight:latest
        container_name: redis_insight
        ports:
            - "5540:5540"
        networks:
            - app-pos-network
        depends_on:
            - redis
        environment:
            - REDIS_URI=redis://redis:6379
    # ===================== KAFKA + ZOOKEEPER =====================
    zookeeper:
        image: confluentinc/cp-zookeeper:7.5.0
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"
        volumes:
            - ./zookeeper-data:/var/lib/zookeeper/data
        networks:
            - app-pos-network

    kafka:
        image: confluentinc/cp-kafka:7.5.0
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - app-pos-network
# ===================== SPRING BOOT (BACKEND) =====================
    pos-backend:
        build: ./pos-be
        container_name: pos-backend
        ports:
            - "8080:8080"
        env_file:
            - ./pos-be/.env
        depends_on:
            - app-pos-postgres
            - redis
            - kafka
        volumes:
            - ./pos-be/uploads:/app/uploads
        networks:
            - app-pos-network
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
          interval: 30s
          timeout: 10s
          retries: 3
# ===================== REACT FRONTEND =====================
    pos-frontend:
        build:
            context: ./pos-fe
            dockerfile: Dockerfile
        container_name: pos-frontend
        ports:
            - "5173:5173"
        volumes:
            - ./pos-fe:/app
            - /app/node_modules
        command: npm run dev
        stdin_open: true
        tty: true
        depends_on:
            - pos-backend
        networks:
            - app-pos-network
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:5173"]
          interval: 30s
          timeout: 10s
          retries: 3

volumes:
    app-pos-pgdata:
    redis-data:

networks:
    app-pos-network:
        driver: bridge